# Collections
collections:
  slides :
    output: false
  decks :
    output: true

defaults:
  - scope:
      type: decks
    values:
      layout: deck
      theme: white
      transition: slide
  - scope:
      path: "_slides/01"
      type: slides
    values:
      category: kyrie
  - scope:
      path: "_slides/02"
      type: slides
    values:
      category: gloria
