# Collections
collections:
  slides :
    output: true
    permalink: /:path/
  decks :
    output: true
    permalink: /:path/
  cursus :
    output: true
    permalink: /:path/

defaults:
  - scope:
      type: decks
    values:
      layout: deck
      theme: clever
      transition: fade
  - scope:
      type: slides
    values:
      layout: slide
  - scope:
      type: cursus
    values:
      layout: cursus
