# Collections
collections:
  slides :
    output: true
  decks :
    output: true
  cursus :
    output: true

defaults:
  - scope:
      type: decks
    values:
      layout: deck
      theme: white
      transition: slide
  - scope:
      type: slides
    values:
      layout: slide
  - scope:
      type: cursus
    values:
      layout: cursus
