# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Decks Template'
email: borisschapira@gmail.com
description: "an example of how you can use Jekyll to manage different training programs"
baseurl: "/decks-template" # the subpath of your site, e.g. /blog
timezone: Europe/Paris
incremental: true
profile: true
encoding: utf-8

# Build settings
markdown: kramdown

# Exclusions
exclude:
  - ".cache"
  - "scripts"
  - "tasks"
  - "autoprefixer.yml"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE.md"
  - "README.md"
  - "Rakefile"
  - "tmp"
  - "vendor"
include:
  - ".well-known"
  - ".htaccess"

gems:
  - jekyll-assets

assets:
  compress:
    css: false
    js: false
  cache: false
  prefix: "/assets"
  sources:
    - "assets/"

emoji:
  src: "/assets"
